name: Build Docker Image

on: workflow_dispatch

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (optional, for pushing images) 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t engineering-tools:latest .

      # Step 4: Tag the image (optional)
      - name: Tag Docker Image
        run: docker tag engineering-tools:latest bradmoffat/engineering-tools:latest

      # Step 5: Push the Docker image to Docker Hub (optional)
      - name: Push Docker Image
        run: docker push bradmoffat/engineering-tools:latest
