name: Build Docker Image

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (optional, for pushing images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t bradmoffat/engineering-tools:latest .

      # Step 4: Push the Docker image to Docker Hub (optional)
      - name: Push Docker Image
        run: docker push bradmoffat/engineering-tools:latest
